export const events = [
  {
    image: "/images/event1.png",
    title: "NextJS Global Summit 2025",
    slug: "nextjs-global-summit-2025",
    location: "San Francisco, CA",
    date: "March 15, 2025",
    time: "9:00 AM - 6:00 PM PST",
  },
  {
    image: "/images/event2.png",
    title: "React Developers Meetup",
    slug: "react-developers-meetup",
    location: "Austin, TX",
    date: "March 22, 2025",
    time: "6:30 PM - 9:00 PM CST",
  },
  {
    image: "/images/event3.png",
    title: "AI & Web3 Hackathon",
    slug: "ai-web3-hackathon",
    location: "New York, NY",
    date: "April 5-7, 2025",
    time: "48-hour event starting 9:00 AM EST",
  },
  {
    image: "/images/event4.png",
    title: "TypeScript Workshop: Advanced Patterns",
    slug: "typescript-advanced-patterns",
    location: "Seattle, WA",
    date: "April 12, 2025",
    time: "10:00 AM - 4:00 PM PST",
  },
  {
    image: "/images/event5.png",
    title: "DevOps & Cloud Infrastructure Conference",
    slug: "devops-cloud-conference",
    location: "Denver, CO",
    date: "April 18-19, 2025",
    time: "8:00 AM - 7:00 PM MST (both days)",
  },
  {
    image: "/images/event6.png",
    title: "Frontend Masters Coding Challenge",
    slug: "frontend-masters-challenge",
    location: "Online (Global)",
    date: "May 1, 2025",
    time: "12:00 PM - 12:00 AM UTC",
  },
];
